alter session set current_schema = U_DM;
BEGIN
    --PKG_ETL_COUPONS_SAL.LOAD_COUPONS_SAL();
    --PKG_ETL_GEO_SAL.LOAD_GEO_SAL();
    --PKG_ETL_PRODUCTS_SAL.LOAD_PRODUCTS_SAL();
    PKG_ETL_FCT_SALES_SAL.LOAD_FCT_SALES_SAL();
END;
