--DROP SEQUENCE DW_DATA.SEQ_DIM_PRODUCTS
CREATE SEQUENCE DW_DATA.SEQ_DIM_PRODUCTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_DIM_COUPONS
CREATE SEQUENCE DW_DATA.SEQ_DIM_COUPONS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_DIM_GEO
CREATE SEQUENCE DW_DATA.SEQ_DIM_GEO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_DIM_RESTAURANTS
CREATE SEQUENCE DW_DATA.SEQ_DIM_RESTAURANTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_DIM_PERIODS
CREATE SEQUENCE DW_DATA.SEQ_DIM_PERIODS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_FCT_SALES
CREATE SEQUENCE DW_DATA.SEQ_FCT_SALES
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;