-- TABLESPACE AND USER CREATION

CREATE TABLESPACE GEO_BACKUP
DATAFILE '/oracle/u02/oradata/EMastykinadb/ts_geo_backup.dat'
SIZE 150M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;


CREATE USER SB_MBackUp IDENTIFIED BY "PWD"
DEFAULT TABLESPACE GEO_BACKUP;

GRANT CONNECT,RESOURCE TO SB_MBackUp;
GRANT SELECT ANY TABLE TO SB_MBackUp;

ALTER USER SB_MBackUp QUOTA UNLIMITED ON GEO_BACKUP;
