CREATE TABLE TRANSACTIONS(
    PRODUCT_NAME       VARCHAR2(40 BYTE) ,
    PRODUCT_DESC       VARCHAR2(40 BYTE),
    CATEGORY_ID        NUMBER(*, 0),
    CATEGORY_NAME      VARCHAR2(40 BYTE),
    CATEGORY_DESC      VARCHAR2(40 BYTE),
    SUBCATEGORY_ID     NUMBER(*, 0),
    SUBCATEGORY_NAME   VARCHAR2(40 BYTE),
    SUBCATEGORY_DESC   VARCHAR2(40 BYTE),
    FEATURE_ID         NUMBER(*, 0),
    FEATURE_NAME       VARCHAR2(40 BYTE),
    FEATURE_DESC       VARCHAR2(40 BYTE),
    COST_DOLLAR_AMOUNT NUMBER(5,3),
    PHONE              VARCHAR2(40 BYTE),
    POSTAL_CODE        NUMBER(10,0) ,
    ADDRESS            VARCHAR2(40 BYTE) ,
    COUPON_NAME                  VARCHAR2(40),
    COUPON_DESC                  VARCHAR2(40),
    MEDIA_TYPE_ID                NUMBER(*,0) ,
    MEDIA_TYPE                   VARCHAR2(40),
    DISCOUNT_PERCENTAGE_AMOUNT   NUMBER(4,2),
    VALID_FROM                   DATE ,
    VALID_TO                     DATE ,
    COUNTRY_NAME         CHAR(40),
    REGION_NAME          CHAR(40),
    CITY_NAME            CHAR(40),
    PERIOD_NAME VARCHAR2(20),
    PERIOD_DESC VARCHAR2(40),
    BEGIN_DT    DATE DEFAULT TO_DATE('01/01/1990', 'DD/MM/YYYY'),
    END_DT      DATE DEFAULT TO_DATE('31/12/9999', 'DD/MM/YYYY'),
    INSERT_DT   DATE
);


INSERT INTO TRANSACTIONS(PRODUCT_NAME, PRODUCT_DESC, CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESC,
       SUBCATEGORY_ID, SUBCATEGORY_NAME, SUBCATEGORY_DESC,
       FEATURE_ID, FEATURE_NAME, FEATURE_DESC, COST_DOLLAR_AMOUNT,
       PHONE, POSTAL_CODE, ADDRESS, COUPON_NAME,
       COUPON_DESC, MEDIA_TYPE_ID, MEDIA_TYPE,
       DISCOUNT_PERCENTAGE_AMOUNT, VALID_FROM,VALID_TO,
       COUNTRY_NAME, REGION_NAME, CITY_NAME,
       PERIOD_NAME, PERIOD_DESC, BEGIN_DT, END_DT)
WITH
CTE_PRODUCTS_COUPONS_RESTAURANTS AS (
     SELECT  P.PRODUCT_NAME, PRODUCT_DESC,
        P.CATEGORY_ID, P.CATEGORY_NAME, P.CATEGORY_DESC,
        P.SUBCATEGORY_ID, P.SUBCATEGORY_NAME, P.SUBCATEGORY_DESC,
        P.FEATURE_ID, P.FEATURE_NAME, P.FEATURE_DESC,P.COST_DOLLAR_AMOUNT,
        R.PHONE, R.POSTAL_CODE, R.ADDRESS,
        C.COUPON_NAME, C.COUPON_DESC, C.MEDIA_TYPE_ID, C.MEDIA_TYPE, C.DISCOUNT_PERCENTAGE_AMOUNT,C.VALID_FROM,
        C.VALID_TO,
        TRUNC(DBMS_RANDOM.VALUE(1,3648)) AS GEO_ID,
        TRUNC(DBMS_RANDOM.VALUE(1,100)) AS PERIOD_ID
FROM SA_PRODUCTS_DATA P CROSS JOIN  SA_COUPONS_DATA C, SA_RESTAURANTS_DATA R ORDER BY dbms_random.value
FETCH FIRST 300000 ROWS ONLY
),
CTE_GEO AS (
     SELECT COUNTRY_NAME, REGION_NAME, CITY_NAME, ROWNUM AS GEO_ID FROM SA_GEO_DATA
),
CTE_PERIODS AS (
     SELECT PERIOD_NAME, PERIOD_DESC, BEGIN_DT, END_DT,  ROWNUM AS PERIOD_ID  FROM SA_PERIODS_DATA
)
SELECT PRODUCT_NAME, PRODUCT_DESC, CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESC,
       SUBCATEGORY_ID, SUBCATEGORY_NAME, SUBCATEGORY_DESC,
       FEATURE_ID, FEATURE_NAME, FEATURE_DESC,COST_DOLLAR_AMOUNT,
       PHONE, POSTAL_CODE, ADDRESS, COUPON_NAME,
       COUPON_DESC, MEDIA_TYPE_ID, MEDIA_TYPE,
       DISCOUNT_PERCENTAGE_AMOUNT, VALID_FROM,VALID_TO,
       COUNTRY_NAME, REGION_NAME, CITY_NAME,
       PERIOD_NAME, PERIOD_DESC, BEGIN_DT, END_DT
    FROM CTE_PRODUCTS_COUPONS_RESTAURANTS
    INNER JOIN  CTE_GEO ON CTE_GEO.GEO_ID = CTE_PRODUCTS_COUPONS_RESTAURANTS.GEO_ID
    INNER JOIN  CTE_PERIODS ON CTE_PERIODS.PERIOD_ID = CTE_PRODUCTS_COUPONS_RESTAURANTS.PERIOD_ID;
COMMIT;
