--DROP SEQUENCE DW_DATA.SEQ_PRODUCTS
CREATE SEQUENCE DW_DATA.SEQ_PRODUCTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_COUPONS
CREATE SEQUENCE DW_DATA.SEQ_COUPONS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--DROP SEQUENCE DW_DATA.SEQ_GEO
CREATE SEQUENCE DW_DATA.SEQ_GEO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


DROP SEQUENCE DW_DATA.SEQ_SALES
CREATE SEQUENCE DW_DATA.SEQ_SALES
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;