alter session set current_schema = DW_CL;
BEGIN
    PKG_ETL_SALES_CL.LOAD_CLEAN_SALES();
   -- PKG_ETL_GEO_CL.LOAD_CLEAN_GEO();
    PKG_ETL_COUPONS_CL.LOAD_CLEAN_COUPONS();
    --PKG_ETL_PRODUCTS_CL.LOAD_CLEAN_PRODUCTS();
END;
